const BASE = import.meta.env.VITE_API_BASE || '';

export const ENDPOINTS = {
  CONFIG_LOAD: `${BASE}/api/config`,
  CONFIG_SAVE: `${BASE}/api/config`,
  AI_CHAT: `${BASE}/api/ai/chat`,
  AI_REQUEST_JSON: `${BASE}/api/ai/request-json`,
  FILE_PARSE: `${BASE}/api/file/parse`,
  TECHNICAL_PLAN_LOAD_STATE: `${BASE}/api/technical-plan/state`,
  TECHNICAL_PLAN_IMPORT_TENDER: `${BASE}/api/technical-plan/import-tender`,
  TECHNICAL_PLAN_IMPORT_ORIGINAL_PLAN: `${BASE}/api/technical-plan/import-original-plan`,
  TECHNICAL_PLAN_SELECT_BID_SECTION: `${BASE}/api/technical-plan/select-bid-section`,
  TECHNICAL_PLAN_CANCEL_BID_SECTION: `${BASE}/api/technical-plan/cancel-bid-section`,
  TECHNICAL_PLAN_READ_TENDER_MARKDOWN: `${BASE}/api/technical-plan/tender-markdown`,
  TECHNICAL_PLAN_READ_ORIGINAL_PLAN_MARKDOWN: `${BASE}/api/technical-plan/original-plan-markdown`,
  TECHNICAL_PLAN_UPDATE_STEP: `${BASE}/api/technical-plan/update-step`,
  TECHNICAL_PLAN_SET_WORKFLOW_KIND: `${BASE}/api/technical-plan/set-workflow-kind`,
  TECHNICAL_PLAN_SAVE_BID_ANALYSIS_CONFIG: `${BASE}/api/technical-plan/bid-analysis-config`,
  TECHNICAL_PLAN_SAVE_OUTLINE_CONFIG: `${BASE}/api/technical-plan/outline-config`,
  TECHNICAL_PLAN_SAVE_OUTLINE: `${BASE}/api/technical-plan/outline`,
  TECHNICAL_PLAN_SAVE_GLOBAL_FACTS: `${BASE}/api/technical-plan/global-facts`,
  TECHNICAL_PLAN_SAVE_CONTENT_OPTIONS: `${BASE}/api/technical-plan/content-options`,
  TECHNICAL_PLAN_SAVE_CHAPTER_CONTENT: `${BASE}/api/technical-plan/chapter-content`,
  TECHNICAL_PLAN_CLEAR: `${BASE}/api/technical-plan/clear`,
  TASKS_START_BID_ANALYSIS: `${BASE}/api/tasks/bid-analysis`,
  TASKS_START_OUTLINE_GENERATION: `${BASE}/api/tasks/outline-generation`,
  TASKS_START_GLOBAL_FACTS: `${BASE}/api/tasks/global-facts`,
  TASKS_START_CONTENT_GENERATION: `${BASE}/api/tasks/content-generation`,
  TASKS_PAUSE_CONTENT_GENERATION: `${BASE}/api/tasks/pause-content-generation`,
  TASKS_EVENTS: `${BASE}/api/tasks/events`,
  EXPORT_WORD: `${BASE}/api/export/word`,
  EXPORT_WORD_PROGRESS: `${BASE}/api/export/word/progress`,
  KNOWLEDGE_BASE_LIST: `${BASE}/api/knowledge-base`,
  KNOWLEDGE_BASE_READ_MARKDOWN: `${BASE}/api/knowledge-base/markdown`,
} as const;
